radar/disease_groups/models.py
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from radar.database import db


class DiseaseGroup(db.Model):
    __tablename__ = 'disease_groups'

    id = Column(Integer, primary_key=True)
    name = Column(String)

    patients = relationship('DiseaseGroupPatient')
    users = relationship('DiseaseGroupUser')
    features = relationship('DiseaseGroupFeatures', backref='disease_group')

    def has_feature(self, feature_name):
        return any(x.feature_name == feature_name for x in self.features)

    def can_view_patient(self, user):
        if user.is_admin:
            return True

        for disease_group_user in user.disease_groups:
            if disease_group_user.disease_group == self and disease_group_user.has_view_patient_permission:
                return True

        return False


class DiseaseGroupFeatures(db.Model):
    __tablename__ = 'disease_group_features'

    id = Column(Integer, primary_key=True)
    disease_group_id = Column(Integer, ForeignKey('disease_groups.id'))
    feature_name = Column(String, nullable=False)

radar/models/base.py
from sqlalchemy import Integer, Column, String, ForeignKey, UniqueConstraint, DateTime, func
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import relationship

from radar.lib.database import db


class Facility(db.Model):
    __tablename__ = 'facilities'

    id = Column(Integer, primary_key=True)
    code = Column(String, unique=True)
    name = Column(String)


class DataSource(db.Model):
    __tablename__ = 'data_sources'

    id = Column(Integer, primary_key=True)
    type = Column(String)

    sda_bundle = relationship('SDABundle', uselist=False, cascade='all, delete-orphan')

    def view_url(self):
        return None

    def edit_url(self):
        return None

    def delete_url(self):
        return None

    def can_view(self, user):
        _ = user
        return False

    def can_edit(self, user):
        _ = user
        return False

    __mapper_args__ = {
        'polymorphic_identity': 'data_sources',
        'polymorphic_on': type
    }


class DataImport(DataSource):
    __tablename__ = 'data_imports'

    id = Column(Integer, ForeignKey('data_sources.id'), primary_key=True)

    patient_id = Column(Integer, ForeignKey('patients.id', ondelete='CASCADE', onupdate='CASCADE'))
    patient = relationship('Patient')

    facility_id = Column(Integer, ForeignKey('facilities.id'))
    facility = relationship('Facility')

    __mapper_args__ = {
        'polymorphic_identity': 'data_imports',
    }

    __table_args__ = (
        UniqueConstraint('patient_id', 'facility_id'),
    )


class CreatedMixin(object):
    @declared_attr
    def created_user_id(cls):
        return Column(Integer, ForeignKey('users.id'))

    @declared_attr
    def created_user(cls):
        return relationship('User', foreign_keys=[cls.created_user_id])

    @declared_attr
    def created_at(cls):
        return Column(DateTime(timezone=True), server_default=func.now())


class ModifiedMixin(object):
    @declared_attr
    def modified_user_id(cls):
        return Column(Integer, ForeignKey('users.id'))

    @declared_attr
    def modified_user(cls):
        return relationship('User', foreign_keys=[cls.modified_user_id])

    @declared_attr
    def modified_at(cls):
        return Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.current_timestamp())


class MetadataMixin(CreatedMixin, ModifiedMixin):
    pass


class PatientMixin(object):
    @declared_attr
    def patient_id(cls):
        return Column(Integer, ForeignKey('patients.id', ondelete='CASCADE', onupdate='CASCADE'))

    @declared_attr
    def patient(cls):
        return relationship('Patient')


class DiseaseGroupMixin(object):
    @declared_attr
    def disease_group_id(cls):
        return Column(Integer, ForeignKey('disease_groups.id'))

    @declared_attr
    def disease_group(cls):
        return relationship('DiseaseGroup')


class UnitMixin(object):
    @declared_attr
    def unit_id(cls):
        return Column(Integer, ForeignKey('units.id'))

    @declared_attr
    def unit(cls):
        return relationship('Unit')


class LookupTableMixin(object):
    @declared_attr
    def id(cls):
        return Column(Integer, primary_key=True)

    @declared_attr
    def name(cls):
        return Column(String)

    @classmethod
    def choices(cls, session):
        return [(x.id, x.name, x) for x in session.query(cls).order_by(cls.name).all()]


class StringLookupTableMixin(object):
    @declared_attr
    def id(cls):
        return Column(String, primary_key=True)

    @declared_attr
    def name(cls):
        return Column(String)

    @classmethod
    def choices(cls, session):
        return [(x.id, x.name, x) for x in session.query(cls).order_by(cls.name).all()]

radar/models/disease_groups.py
from sqlalchemy import Column, Integer, String, ForeignKey, Boolean, UniqueConstraint
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship

from radar.lib.database import db
from radar.lib.roles import DISEASE_GROUP_VIEW_DEMOGRAPHICS_ROLES, DISEASE_GROUP_VIEW_PATIENT_ROLES, \
    DISEASE_GROUP_VIEW_USER_ROLES, DISEASE_GROUP_MANAGED_ROLES, DISEASE_GROUP_ROLE_NAMES
from radar.models.common import MetadataMixin


class DiseaseGroup(db.Model):
    __tablename__ = 'disease_groups'

    id = Column(Integer, primary_key=True)
    name = Column(String)

    disease_group_patients = relationship('DiseaseGroupPatient')
    disease_group_users = relationship('DiseaseGroupUser')
    features = relationship('DiseaseGroupFeature')
    disease_group_result_group_definitions = relationship('DiseaseGroupResultGroupDefinition')

    @property
    def patients(self):
        return [x.patient for x in self.disease_group_patients]

    @property
    def users(self):
        return [x.user for x in self.disease_group_users]

    @property
    def result_group_definitions(self):
        return [x.result_group_definition for x in self.disease_group_result_group_definitions]

    def has_feature(self, name):
        return any(x.name == name for x in self.features)

    def can_view_patient(self, user):
        if user.is_admin:
            return True

        for disease_group_user in user.disease_groups:
            if disease_group_user.disease_group == self and disease_group_user.has_view_patient_permission:
                return True

        return False


class DiseaseGroupFeature(db.Model):
    __tablename__ = 'disease_group_features'

    id = Column(Integer, primary_key=True)

    disease_group_id = Column(Integer, ForeignKey('disease_groups.id'))
    disease_group = relationship('DiseaseGroup')

    name = Column(String, nullable=False)
    weight = Column(Integer, nullable=False)


class DiseaseGroupPatient(db.Model, MetadataMixin):
    __tablename__ = 'disease_group_patients'

    id = Column(Integer, primary_key=True)

    disease_group_id = Column(Integer, ForeignKey('disease_groups.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False)
    disease_group = relationship('DiseaseGroup')

    patient_id = Column(Integer, ForeignKey('patients.id', ondelete='CASCADE', onupdate='CASCADE'), nullable=False)
    patient = relationship('Patient')

    is_active = Column(Boolean, nullable=False, default=True, server_default='1')

    __table_args__ = (
        UniqueConstraint('disease_group_id', 'patient_id'),
    )

    def can_edit(self, current_user):
        # TODO
        return self.patient.can_edit(current_user)


class DiseaseGroupUser(db.Model):
    __tablename__ = 'disease_group_users'

    id = Column(Integer, primary_key=True)
    disease_group_id = Column(Integer, ForeignKey('disease_groups.id'), nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    role = Column(String, nullable=False)

    user = relationship('User')
    disease_group = relationship('DiseaseGroup')

    __table_args__ = (
        UniqueConstraint('disease_group_id', 'user_id'),
    )

    @hybrid_property
    def has_view_demographics_permission(self):
        return self.role in DISEASE_GROUP_VIEW_DEMOGRAPHICS_ROLES

    @hybrid_property
    def has_view_patient_permission(self):
        return self.role in DISEASE_GROUP_VIEW_PATIENT_ROLES

    @hybrid_property
    def has_view_user_permission(self):
        return self.role in DISEASE_GROUP_VIEW_USER_ROLES

    @property
    def has_edit_user_membership_permission(self):
        managed_roles = DISEASE_GROUP_MANAGED_ROLES.get(self.role)
        return managed_roles is not None and len(managed_roles) > 0

    def can_edit(self, user):
        # TODO
        return True

    @property
    def role_name(self):
        return DISEASE_GROUP_ROLE_NAMES.get(self.role)


class DiseaseGroupResultGroupDefinition(db.Model):
    __tablename__ = 'disease_group_result_group_definitions'

    id = Column(Integer, primary_key=True)

    disease_group_id = Column(Integer, ForeignKey('disease_groups.id'), nullable=False)
    disease_group = relationship('DiseaseGroup')

    result_group_definition_id = Column(Integer, ForeignKey('result_group_definitions.id'), nullable=False)
    result_group_definition = relationship('ResultGroupDefinition')

    weight = Column(Integer, nullable=False)

    __table_args__ = (
        UniqueConstraint('disease_group_id', 'result_group_definition_id'),
    )

radar/models/news.py
from sqlalchemy import Column, Integer, Text, DateTime

from radar.lib.database import db


class Post(db.Model):
    __tablename__ = 'posts'

    id = Column(Integer, primary_key=True)
    title = Column(Text, nullable=False)
    body = Column(Text, nullable=False)
    published = Column(DateTime(timezone=True), nullable=False)

    def can_view(self, user):
        return True

    def can_edit(self, user):
        return user.is_admin

radar/models/posts.py
from sqlalchemy import Column, Integer, Text, DateTime

from radar.lib.database import db


# TODO add metadata


class Post(db.Model):
    __tablename__ = 'posts'

    id = Column(Integer, primary_key=True)
    title = Column(Text, nullable=False)
    body = Column(Text, nullable=False)
    published = Column(DateTime(timezone=True), nullable=False)

    def can_view(self, user):
        return True

    def can_edit(self, user):
        return user.is_admin

radar/models/units.py
from sqlalchemy import Column, Integer, String, ForeignKey, Boolean, UniqueConstraint
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship

from radar.lib.database import db
from radar.lib.roles import UNIT_VIEW_DEMOGRAPHICS_ROLES, UNIT_VIEW_PATIENT_ROLES, UNIT_EDIT_PATIENT_ROLES, \
    UNIT_VIEW_USER_ROLES, UNIT_MANAGED_ROLES, UNIT_RECRUIT_PATIENT_ROLES, UNIT_ROLE_NAMES
from radar.models.common import MetadataMixin


class Unit(db.Model):
    __tablename__ = 'units'

    id = Column(Integer, primary_key=True)
    name = Column(String)

    facilities = relationship('Facility')
    unit_patients = relationship('UnitPatient')
    unit_users = relationship('UnitUser')

    @property
    def internal_facilities(self):
        return [x for x in self.facilities if x.is_internal]


class UnitPatient(db.Model, MetadataMixin):
    __tablename__ = 'unit_patients'

    id = Column(Integer, primary_key=True)

    unit_id = Column(Integer, ForeignKey('units.id'), nullable=False)
    unit = relationship('Unit')

    patient_id = Column(Integer, ForeignKey('patients.id'), nullable=False)
    patient = relationship('Patient')

    is_active = Column(Boolean, nullable=False, default=True, server_default='1')

    __table_args__ = (
        UniqueConstraint('unit_id', 'patient_id'),
    )

    def can_edit(self, current_user):
        # TODO
        return self.patient.can_edit(current_user)


class UnitUser(db.Model):
    __tablename__ = 'unit_users'

    id = Column(Integer, primary_key=True)
    unit_id = Column(Integer, ForeignKey('units.id'), nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    role = Column(String, nullable=False)

    unit = relationship('Unit')
    user = relationship('User')

    __table_args__ = (
        UniqueConstraint('unit_id', 'user_id'),
    )

    @hybrid_property
    def has_view_demographics_permission(self):
        return self.role in UNIT_VIEW_DEMOGRAPHICS_ROLES

    @hybrid_property
    def has_view_patient_permission(self):
        return self.role in UNIT_VIEW_PATIENT_ROLES

    @hybrid_property
    def has_edit_patient_permission(self):
        return self.role in UNIT_EDIT_PATIENT_ROLES

    @hybrid_property
    def has_view_user_permission(self):
        return self.role in UNIT_VIEW_USER_ROLES

    @property
    def has_edit_user_membership_permission(self):
        managed_roles = UNIT_MANAGED_ROLES.get(self.role)
        return managed_roles is not None and len(managed_roles) > 0

    @hybrid_property
    def has_recruit_patient_permission(self):
        return self.role in UNIT_RECRUIT_PATIENT_ROLES

    @property
    def role_name(self):
        return UNIT_ROLE_NAMES.get(self.role)

    def can_edit(self, user):
        # TODO
        return True

radar/news/models.py
from sqlalchemy import Column, Integer, Text, DateTime
from radar.database import db


class Story(db.Model):
    __tablename__ = 'news'

    id = Column(Integer, primary_key=True)
    title = Column(Text, nullable=False)
    body = Column(Text, nullable=False)
    published = Column(DateTime(timezone=True), nullable=False)

    def can_edit(self, user):
        return user.is_admin

radar/patients/diagnosis/models.py
from radar.models import DataSource, DiseaseGroupMixin, PatientMixin, CreatedModifiedMixin
from sqlalchemy import Column, Integer, ForeignKey


class Diagnosis(DataSource, DiseaseGroupMixin, PatientMixin, CreatedModifiedMixin):
    __tablename__ = 'diagnosis'

    id = Column(Integer, ForeignKey('data_sources.id'), primary_key=True)

    def can_view(self, user):
        return self.patient.can_view(user)

    def can_edit(self, user):
        return self.patient.can_edit(user)

    __mapper_args__ = {
        'polymorphic_identity': 'diagnosis',
    }

radar/patients/dialysis/models.py
from sqlalchemy import Column, Integer, ForeignKey, Date
from sqlalchemy.orm import relationship

from radar.database import db
from radar.models import DataSource, PatientMixin, CreatedModifiedMixin, UnitMixin, LookupTableMixin
from radar.patients.dialysis.concepts import DialysisToDialysisConcept


class Dialysis(DataSource, PatientMixin, CreatedModifiedMixin, UnitMixin):
    __tablename__ = 'dialysis'

    id = Column(Integer, ForeignKey('data_sources.id'), primary_key=True)

    from_date = Column(Date, nullable=False)
    to_date = Column(Date)
    dialysis_type_id = Column(Integer, ForeignKey('dialysis_types.id'), nullable=False)
    dialysis_type = relationship('DialysisType')

    def to_concepts(self):
        return [
            DialysisToDialysisConcept(self)
        ]

    __mapper_args__ = {
        'polymorphic_identity': 'dialysis',
    }

    def can_view(self, user):
        return self.patient.can_view(user)

    def can_edit(self, user):
        return self.patient.can_edit(user)


class DialysisType(db.Model, LookupTableMixin):
    __tablename__ = 'dialysis_types'

radar/patients/genetics/models.py
from radar.models import DataSource, CreatedModifiedMixin, PatientMixin, DiseaseGroupMixin
from sqlalchemy import Column, Integer, ForeignKey, String, Text, DateTime


class Genetics(DataSource, CreatedModifiedMixin, PatientMixin, DiseaseGroupMixin):
    __tablename__ = 'genetics'

    id = Column(Integer, ForeignKey('data_sources.id'), primary_key=True)

    sample_sent_date = Column(DateTime(timezone=True))
    laboratory = Column(String)
    laboratory_reference_number = Column(String)
    results = Column(Text)

    def can_view(self, user):
        return self.patient.can_view(user)

    def can_edit(self, user):
        return self.patient.can_edit(user)

    __mapper_args__ = {
        'polymorphic_identity': 'genetics',
    }

radar/patients/hospitalisation/models.py
from radar.models import DataSource, PatientMixin, CreatedModifiedMixin, UnitMixin
from sqlalchemy import Column, Integer, ForeignKey, DateTime, Text


class Hospitalisation(DataSource, PatientMixin, CreatedModifiedMixin, UnitMixin):
    __tablename__ = 'hospitalisations'

    id = Column(Integer, ForeignKey('data_sources.id'), primary_key=True)

    date_of_admission = Column(DateTime(timezone=True))
    date_of_discharge = Column(DateTime(timezone=True))
    reason_for_admission = Column(Text)
    comments = Column(Text)

    def can_view(self, user):
        return self.patient.can_view(user)

    def can_edit(self, user):
        return self.patient.can_edit(user)

    __mapper_args__ = {
        'polymorphic_identity': 'hospitalisations',
    }

radar/patients/pathology/models.py
from radar.models import DataSource, PatientMixin, CreatedModifiedMixin
from sqlalchemy import Column, Integer, ForeignKey


class Pathology(DataSource, PatientMixin, CreatedModifiedMixin):
    __tablename__ = 'pathology'

    id = Column(Integer, ForeignKey('data_sources.id'), primary_key=True)

    def can_view(self, user):
        return self.patient.can_view(user)

    def can_edit(self, user):
        return self.patient.can_edit(user)

    __mapper_args__ = {
        'polymorphic_identity': 'pathology',
    }

radar/views.py
from flask import render_template, Blueprint

from radar.models.news import Story
from radar.auth.forms import LoginForm


bp = Blueprint('radar', __name__)


@bp.route('/')
def index():
    login_form = LoginForm()

    stories = Story.query.order_by(Story.published.desc()).limit(3).all()

    context = dict(
        login_form=login_form,
        stories=stories,
    )

    return render_template('index.html', **context)

radar/web/templates/account.html
{% extends 'simple.html' %}

{% from 'macros/forms.html' import render_field %}
{% from 'macros/forms.html' import render_form_errors %}
{% from 'macros/panels.html' import render_panel %}

{% set current_page = 'account' %}
{% set title = 'Account' %}

{% block content %}
    <h1 class="page-header">Account</h1>

    <table class="table kv">
        <tr>
            <th width="20%">Username</th>
            <td>{{ current_user.username }}</td>
        </tr>

        <tr>
            <th width="20%">Email</th>
            <td>{{ current_user.email }}</td>
        </tr>

        <tr>
            <th width="20%">First Name</th>
            <td>{{ current_user.first_name | missing }}</td>
        </tr>

        <tr>
            <th width="20%">Last Name</th>
            <td>{{ current_user.last_name | missing }}</td>
        </tr>

        <tr>
            <th width="20%">Registered</th>
            <td>{{ current_user.created_date | date_format | missing }}</td>
        </tr>

        {% if current_user.is_admin %}
            <tr>
                <th>Admin</th>
                <td><span class="glyphicon glyphicon-ok"></span></td>
            </tr>
        {% endif %}
    </table>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">User Details</h3>
        </div>

        <div class="panel-body">
            {{ render_form_errors(account_form) }}

            <form method="POST">
                {{ account_form.hidden_tag() }}

                {{ render_field(account_form.first_name) }}
                {{ render_field(account_form.last_name) }}

                <button type="submit" class="btn btn-success" name="account-submit">Save</button>
            </form>
        </div>
    </div>

    <div id="change-email" class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Change Email</h3>
        </div>

        <div class="panel-body">
            {{ render_form_errors(change_email_form) }}

            <form method="POST">
                {{ change_email_form.hidden_tag() }}

                {{ render_field(change_email_form.password) }}
                {{ render_field(change_email_form.new_email) }}
                {{ render_field(change_email_form.new_email_confirm) }}

                <button type="submit" class="btn btn-success" name="change-email-submit">Save</button>
            </form>
        </div>
    </div>

    <div id="change-password" class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Change Password</h3>
        </div>

        <div class="panel-body">
            {{ render_form_errors(change_password_form) }}

            <form method="POST">
                {{ change_password_form.hidden_tag() }}

                {{ render_field(change_password_form.password) }}
                {{ render_field(change_password_form.new_password) }}
                {{ render_field(change_password_form.new_password_confirm) }}

                <button type="submit" class="btn btn-success" name="change-password-submit">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

radar/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% if title %}{{ title }} - {% endif %}RaDaR</title>
        <link rel="stylesheet" href="/static/css/style.css">
        <link rel="stylesheet" href="/static/libs/css/jquery-ui.css">
        <link rel="stylesheet" href="/static/libs/css/chosen.min.css">
        <link rel="stylesheet" href="/static/libs/css/bootstrap-sortable.css">

        <!--[if lt IE 9]>
            <script src="/static/libs/js/html5shiv.js"></script>
            <script src="/static/libs/js/respond.src.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="navbar navbar-static-top radar-navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="{{ url_for('radar.index') }}">RaDaR</a>
                </div>

                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% if current_user.is_authenticated() %}
                            {% if navigation.disease_groups %}
                                {% if navigation.disease_groups | length == 1 %}
                                    <li{% if current_disease_group == navigation.disease_groups[0] %} class="active"{% endif %}>
                                        <a href="{{ url_for('disease_groups.view_disease_group', disease_group_id=navigation.disease_groups[0].id) }}">{{ navigation.disease_groups[0].name }}</a>
                                    </li>
                                {% elif navigation.disease_groups | length <= 5 %}
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Disease Groups <span class="caret"></span></a>

                                        <ul class="dropdown-menu" role="menu">
                                            {% for disease_group in navigation.disease_groups %}
                                                <li{% if current_disease_group == disease_group %} class="active"{% endif %}>
                                                    <a href="{{ url_for('disease_groups.view_disease_group', disease_group_id=disease_group.id) }}">{{ disease_group.name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% else %}
                                    <li{% if current_page == 'disease_groups' %} class="active"{% endif %}>
                                        <a href="{{ url_for('disease_groups.view_disease_group_list') }}">Disease Groups</a>
                                    </li>
                                {% endif %}
                            {% endif %}

                            {% if navigation.units %}
                                {% if navigation.units | length == 1 %}
                                    <li{% if current_unit == navigation.units[0] %} class="active"{% endif %}>
                                        <a href="{{ url_for('units.view_unit', unit_id=navigation.units[0].id) }}">{{ navigation.units[0].name }}</a>
                                    </li>
                                {% elif navigation.units | length <= 5 %}
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Units <span class="caret"></span></a>

                                        <ul class="dropdown-menu" role="menu">
                                            {% for unit in navigation.units %}
                                                <li{% if current_unit == unit %} class="active"{% endif %}>
                                                    <a href="{{ url_for('units.view_unit', unit_id=unit.id) }}">{{ unit.name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% else %}
                                    <li{% if current_page == 'units' %} class="active"{% endif %}>
                                        <a href="{{ url_for('units.view_unit_list') }}">Units</a>
                                    </li>
                                {% endif %}
                            {% endif %}

                            {% if current_user.has_view_patient_permission %}
                                <li{% if current_page == 'patients' %} class="active"{% endif %}>
                                    <a href="{{ url_for('patients.view_patient_list') }}">Patients</a>
                                </li>
                            {% endif %}

                            {% if current_user.has_view_user_permission %}
                                <li{% if current_page == 'users' %} class="active"{% endif %}>
                                    <a href="{{ url_for('users.view_user_list') }}">Users</a>
                                </li>
                            {% endif %}

                            <li{% if current_page == 'news' %} class="active"{% endif %}>
                                <a href="{{ url_for('news.view_posts') }}">News</a>
                            </li>

                            <li{% if current_page == 'stats' %} class="active"{% endif %}>
                                <a href="{{ url_for('stats.view_stats') }}">Stats</a>
                            </li>
                        {% else %}
                            <li{% if current_page == 'news' %} class="active"{% endif %}>
                                <a href="{{ url_for('news.view_posts') }}">News</a>
                            </li>
                        {% endif %}
                    </ul>

                    <div class="navbar-right">
                        {% if current_user.is_authenticated() %}
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logged in as {{ current_user.username }} <span class="caret"></span></a>

                                    <ul class="dropdown-menu" role="menu">
                                        <li{% if current_page == 'account' %} class="active"{% endif %}>
                                            <a href="{{ url_for('auth.account') }}">Account</a>
                                        </li>

                                        <li>
                                            <a href="{{ url_for('auth.account') }}#change-email">Change Email</a>
                                        </li>

                                        <li>
                                            <a href="{{ url_for('auth.account') }}#change-password">Change Password</a>
                                        </li>

                                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        {% else %}
                            <ul class="nav navbar-nav">
                                <li{% if current_page == 'login' %} class="active"{% endif %}>
                                    <a href="{{ url_for('auth.login') }}">Login</a>
                                </li>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            {% block body %}{% endblock %}
        </div>

        <div class="footer">
            <p>&copy; <a href="http://www.renalreg.org">UK Renal Registry</a>, <a href="http://www.renal.org">The Renal Association</a></p>
        </div>

        <script src="/static/libs/js/jquery.js"></script>
        <script src="/static/libs/js/bootstrap.js"></script>
        <script src="/static/libs/js/jquery-ui.js"></script>
        <script src="/static/libs/js/chosen.jquery.min.js"></script>
        <script src="/static/libs/js/highcharts.js"></script>
        <script src="/static/libs/js/moment.js"></script>
        <script src="/static/libs/js/bootstrap-sortable.js"></script>

        <script src="/static/js/app.js"></script>

        {% block body_js %}{% endblock %}
    </body>
</html>

radar/web/templates/disease_groups.html
{% extends 'simple.html' %}

{% set current_page = 'disease_groups' %}
{% set title = 'Disease Groups' %}

{% block content %}
    <h1 class="page-header">Disease Groups</h1>

    <ul>
        {% for disease_group, membership in disease_groups %}
            <li><a href="{{ url_for('disease_groups.view_disease_group', disease_group_id=disease_group.id) }}">{{ disease_group.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

radar/web/templates/forgot_password.html
{% extends 'simple.html' %}

{% set title = 'Forgot Password' %}

{% from 'macros/forms.html' import render_field %}
{% from 'macros/forms.html' import render_form_errors %}

{% block content %}
    <h1 class="page-header">Forgot Password</h1>

    {{ render_form_errors(form) }}

    <form method="POST">
        {{ form.hidden_tag() }}

        {{ render_field(form.username) }}

        <button class="btn btn-primary">Reset Password</button>
    </form>
{% endblock %}

radar/web/templates/simple.html
{% extends 'base.html' %}

{% from 'macros/flash.html' import render_flashed_messages %}

{% block body %}
    <div class="block">
        {{ render_flashed_messages() }}

        {% block content %}{% endblock %}
    </div>
{% endblock %}